print(3 * True)
print(-3.1 * True)
print(type("abc" * False))
print(len("abc" * False))

print(False + False)
print(True + False)
print(False + True)
print(True + True)
print(False + True + True + True)
